package org.nikitakapustkin.bank.contracts.errors;

public enum ErrorCode {
    INVALID_ARGUMENT,
    VALIDATION_ERROR,
    NOT_FOUND,
    ALREADY_EXISTS,
    NOT_ENOUGH_MONEY,
    IDEMPOTENCY_CONFLICT,
    CONCURRENT_UPDATE,
    METHOD_NOT_ALLOWED,
    MESSAGE_NOT_READABLE,
    INTERNAL_ERROR
}
